### ISSUE TITLE
图书搜索功能

### ISSUE THREAD

**Issue by awmleer** [haoguangbo/shelfetch#1]
@qzhsjz

**Comment by awmleer** [comment]
分页问题该怎么解决？？ @qzhsjz

**Comment by qzhsjz** [comment]
如果前后端分离的话，只好是写一个专门的接口，后端分页，前端根据一个get参数发请求。其实分页这种事最好是前后端不分离这样来做……

**Comment by awmleer** [comment]
不是学校的接口本身就自带分页么。。

**Comment by qzhsjz** [comment]
你们学校的ALEPH系统自带分页没错，但是不代表别的系统也带分页啊……
分页的存储问题在老代码里已经解决了，我记得我的老代码是直接裸写的WSGI应用，没有用框架……
也就是说，只要前端需要分页的数据，后端就可以回传。
我建议这样：
后端给前端返回书的列表的时候，顺便传上当前页和总页数。
前端翻页的时候不用刷新页面，只用Ajax请求下来数据，然后刷新数据模型就行了。
